#pragma once


enum MAP_AREA_METHODS
{
	METHOD_MA_REGISTER_MAP_OBJECT=1,
	METHOD_MA_UNREGISTER_MAP_OBJECT,
	METHOD_MA_UPDATE_MOVE_STATUS,
	METHOD_MA_SEND_EVENT_MSG_PACKET,
	METHOD_MA_NEW_MAP_OBJECT,
	METHOD_MA_DEL_MAP_OBJECT,
	METHOD_MA_MOVE_STATUS_UPDATE,
	METHOD_MA_EVENT_MSG_PACKET,
	METHOD_MA_HIDE_ON_MAP,
	METHOD_MA_TELEPORT_IN_MAP,
};