#pragma once


enum PLAYER_CHAR_DB_METHODS
{
	METHOD_PCD_ACCOUNT_LOGIN=1,
	METHOD_PCD_ACCOUNT_LOGOUT,
	METHOD_PCD_GET_ACCOUNT_CHAR,
	METHOD_PCD_CREATE_CHAR,
	METHOD_PCD_DELETE_CHAR,
	METHOD_PCD_GET_CHAR_DATA,
	METHOD_PCD_SAVE_CHAR_DATA,		
};