#pragma once

namespace D3DLib{

extern LPCSTR SHARED_LIB_FX;
extern LPCSTR SHARED_PARAM_FX;

extern LPCSTR M2_MODEL_FX;
extern LPCSTR WMO_MODEL_FX;
extern LPCSTR ADT_MODEL_20_FX;
extern LPCSTR ADT_MODEL_30_FX;
extern LPCSTR M2_PARTICLE_FX;
extern LPCSTR M2_RIBBON_FX;
extern LPCSTR ADT_LIQUID_FX;
extern LPCSTR WDL_MODEL_FX;

extern LPCSTR DEFAULT_UI_WIN_RECT_FX_NT;
extern LPCSTR DEFAULT_UI_WIN_RECT_FX_TF;
extern LPCSTR DEFAULT_UI_WIN_RECT_FX;
extern LPCSTR INVERSE_COLOR_FX;
extern LPCSTR TEXT_RECT_FX;

extern LPCSTR DEFAULT_BOARD_FX_NT;
extern LPCSTR DEFAULT_LINE_FX_NT;
extern LPCSTR DEFAULT_BOUND_FRAME_FX_NT;
extern LPCSTR TEXT_TEXTURE_FX_NT;
extern LPCSTR FONT_FX;
}